### ISSUE TITLE
Is there any method to measure recoil ?

### ISSUE THREAD

**Issue by talhauyanik** [hanslhansl/rainbow-six-siege-weapon-statistics#1]
How to measure gun recoil? I shot at the target board at the shooting range with different barrels and counted how many bullets hit the inside of the circle. But I don't think this is an effective way to measure recoil, especially for marksman rifles.

**Comment by hanslhansl** [comment]
I would love to include recoil stats into this spreadsheet but, for the exact same hurdle you encountered, I believe it to be impossible: Recoil isn't just a single value like e.g. weapon damage. There is horizontal recoil, vertical recoil, first shot recoil, recoil randomness, some weapons' recoil increases after a small spray (e.g. LMGs), some weapons heavily drift either to the right or to the left, ...

The recoil in R6 is too complex of a metric to be measured. Even if it could be measured it wouldn't be possible to display the recoil stats in a spreadsheet in any meaningful way. I'm afraid the best way to find out about a weapon's recoil will always be to try it out ingame.

I would welcome it though if you or someone else found a procedure to measure weapon recoil that is both informative as well as realizable.
