### ISSUE TITLE
Display formula for calculating damage dropoff for various weapon types

### ISSUE THREAD

**Issue by YetiHug** [hanslhansl/rainbow-six-siege-weapon-statistics#2]
Would it be possible to add what formulas you used to calculate the damage drop-off of various weapons to the spreadsheet? See image below for an example of what I am requesting:
![image](https://github.com/hanslhansl/rainbow-six-siege-weapon-statistics/assets/118148513/cb9f83ff-727c-4c50-b18f-84af2c97de5b)

**Comment by YetiHug** [comment]
BTW the reddit post you announced the spreadsheet on has been archived (meaning no comments could be added). Hence, I contacted you through github.

**Comment by hanslhansl** [comment]
I am not using any formulas. I collected the damage values at all distances from 5 to 40 meters ingame. A more in depth explanation can be found on the repository's main Github page under 'Damage per bullet'. 

The extended barrel stats however are calculated. Explanation under 'The extended barrel'.
